name: Deploy to Railway

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci

      - name: Run Tests (if any)
        run: npm test || true

      - name: Deploy to Railway
        if: github.ref == 'refs/heads/main'
        uses: amondnet/railway-deploy@v2.0.0
        with:
          railway_token: ${{ secrets.RAILWAY_TOKEN }}
          service_id: ${{ secrets.RAILWAY_SERVICE_ID }}
